### ISSUE TITLE
Implement the beamformer on the Outriggers

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#1046]
We need a tracking beamformer for the Outrigger systems.   Since those systems use AMD MI100's we can use the Pathfinder beamformer kernels.   However there are a lot of moving parts which need to migrated from Pathfinder:

- [ ] Refactor Pathfinder kernels/command object code to support the newer kotekan version
- [ ] Feed the phases/gains into beamformer, depends on #1029 and #1031 and reuses some of the CHIME read gains stages.
- [ ] Write new beam post-processing code to support the TCP send/recv model simlar to CHIME but following the format in #1044 
- [ ] Update the outrigger configs to with all the new stages and updateable config beam pointing, gain file, and bad feed inputs.
