### ISSUE TITLE
Develop API for getting `pint` polyco data into kotekan.

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#1049]
We need to get the gate information into kotekan so that it knows what time samples to select out of the incoming data stream from the X-engine.   The timing information is going to generated by a piece of software called `pint` https://github.com/nanograv/PINT   We need a way to get this data into a format that kotekan can use for gating.  

Currently kotekan already has some gating support for the N^2 data streams.  The existing system for getting polycos into kotekan uses the updatable config system for generating an API which kotekan stages can listen on for updates to the polycos.   The class for storing that data is in `lib/utils/gateSpec.*pp`.   I'm not sure if this spec is sufficient for the advanced types of gating we plan to use with pint, but it would be useful to see what code exists and/or could be extended to support what we need for the Outriggers project. 

This system is required for #1048

**Comment by andrerenard** [comment]
After some discussion we decided the existing API has insufficient flexibility to deal with more complex pulsars.  e.g. millisecond pulsars, pulsars in binary systems, and pulsars with complex burst profiles. 

The proposal is to create a new API which doesn't use polycos, but instead provides a list of start and stop times for the ON gate.  This will require the transfer of more data to kotekan than is normally done via the REST API.  There are two approaches we could use here:
1. We could follow the timing gains model where we pass a tag to kotekan via the JSON REST API, which then retrieves the gains from server by asking for the tag and a given frequency.    This works well for per frequency data.  However it requires creating a server and a fair bit of infrastructure to setup.
2. We could extend the existing REST API to accept binary message.  Because the gate description varies with frequency based only on the dm (and a small correction factor), we do not need different messages for different nodes.  So just POST'ing the same gate description to each node would be sufficient. 

Based on our current discussions, option 2. seems to be the best for this application, since it lowers the complexity of running another server. 

Steps to implement: 

- [ ] Modify the REST server in kotekan to accept binary data 
- [ ] Implement a new singleton class to mange the gate data
- [ ] Create a testing python script to send basic gate descriptions to the new API 
- [ ] Create units tests to make sure the API works as expected

Breaking down in more detail

## REST Server

We need to extend the REST (really a simply HTTP server), to have a new `get_binary_data()` callback on the connection object, and support registering POST callbacks which expect binary data. 

Currently the REST server dynamically assigns memory (which is fine for small messages), but once we move to large messages, we want to support pooled memory, which is reused.  This is to avoid large memory allocations/frees while the system is in operation.  See the `restServer::get_http_message()` and the `restServer` class in general for details of the current system.   There will still be some dynamic memory allocation in the libevents API, but that's likely unavoidable. 

## Singleton class (GateAPIManager)

Because this data lives outside the current updateable config logic, to provides gate information to many different stages we will use the singleton class model.  This is similar to how the `basebandAPIManager`, `restServer`, and `prometheusMetrics` systems currently work. 

The `GateAPIManager` will provide the following high level functionality:

- Register the API with the `restServer`
- Parse incoming API requests
- Add the requests to a queue (with configurable, but fixed length) 
- Provide functions for getting the gate start and stop times (to be used in stages that actually process the raw data and gate it)

The `GateAPIManager` will also deal with the logical of rounding the gate data to FPGA frame/seq numbers, and shifting the gates based on frequency and DM. 

## Testing python script

We need a python script to send basic gate messages to the API to do tests.   Perhaps this is something @aaronpearlman can help with?  It doesn't need to be complicated, just a few gates period to start. 

##  Unit tests

We should look into scripting unit tests for this.  We can get into more detail once the main work is done. 

# API description

Binary message: 

```
uint64_t start_time - uint64_t // microseconds.
float dm
float dm_correction
char[32] pulsar_name
uint32_t array_len
uint32_t start_stop_time_array[array_len] // Array of (start, stop) time pairs.  Stored as deltas in microseconds from the last start or stop time, or the `start_time` if no previous time exists.   Note max delta = 71 minutes. 
```

If the pulse is ON when the observation starts at start_time, set the first start delta to 0.

When providing this data to the stages, it will be more convenient to do it in the base unit of sequence numbers, so data should be rounded to the telescope's base time unit.  In the case of CHIME this is 2.56 microseconds.   Round to maximize the gate width. 

Round to make sure gate width stays the same with each frequency.  Which means do the rounding at the base frequency first and then shifted the rounded values by the per frequency dm offset.

Assume top of the band for reference frequency in the dm offsets.   Can vary with instrument.
