### ISSUE TITLE
Enable CHIME baseband tracking beam recordings on gating node

### ISSUE THREAD

**Issue by aaronpearlman** [kotekan/kotekan#1071]
It would be useful to enable baseband tracking beam recordings on the `outrigger-gating` node in VSOP for development of the gated beam technologies.

The outstanding tasks are:

- [x] Determine if there are outstanding hardware issues that need to be resolved before we can run `kotekan` and receive data on the `outrigger-gating` node (@andrerenard and @shinybrar).
- [x] Ask Shiny if we have a 10.1.50.XXX IP address for outrigger-gating on the correct VLAN.
- [x] Set up static IP, MTU/netplan, and LDAP on `outrigger-gating`. (Andre, Aaron, Shiny)
- [x] Install dependencies for `kotekan` and build `kotekan` on `outrigger-gating` with `BeamAssembly` kotekan stage. (@aaronpearlman)
- [x] Coordinate usage of the unused cosmology beam (@andrerenard). Ask Mandana & Richard to use the unused tracking beam.
- [x] Change IP address in kotekan config (hotfix) to enable data recording: https://github.com/kotekan/kotekan/blob/master/config/chime_science_run_gpu.yaml
- [x] Config update to coco, needs to be coordinated with Mandana/Niko (requires a short system restart to deploy).

* Deploy the new BeamAssembly kotekan stage and verify that the data acquisitions are working as expected (@aaronpearlman and @andrerenard). --> **Optional:** Desired, but not strictly necessary to complete the work in this issue.

**Comment by aaronpearlman** [comment]
Additional steps:

- [ ] Ask Mandana & Richard to use the unused tracking beam.
- [ ] Ask Shiny if we have a 10.1.50.XXX IP address for outrigger-gating on the correct VLAN.
- [ ] Change IP address in kotekan config (hotfix) to enable data recording: https://github.com/kotekan/kotekan/blob/master/config/chime_science_run_gpu.yaml
- [ ] Config update to coco, needs to be coordinated with Mandana/Niko (requires a short system restart to deploy).

**Comment by aaronpearlman** [comment]
Static IP on `enp193s0f1` set to be: 10.1.50.52
Changed to: `MTU 9000` using yaml file: /etc/netplan/00-installer-config.yaml

Note: `sudo netplan apply` is buggy and disabled ssh. But, the change to MTU was successful after rebooting.

LDAP was set up, following the instructions on: https://bao.chimenet.ca/wiki/index.php/User_Management

Set up on the 40 gig connection. This can be verified using `ethtool enp193s0f1`.

Current IP Configuration:

![image](https://user-images.githubusercontent.com/17873558/213579065-7400c426-bebd-4e79-92ca-e63b39d98193.png)

Old IP Configuration:

![image](https://user-images.githubusercontent.com/17873558/213578678-b5a3ad07-2bce-4db7-9ace-5c3c33efaef6.png)

**Comment by aaronpearlman** [comment]
`kotekan` successfully built on `outrigger-gating`. The following dependencies were installed:

```
sudo apt-get install python-yaml
sudo apt-get install libevent-dev
sudo apt-get install python-jinja2
sudo apt-get install cmake
sudo apt-get install libnuma-dev
sudo apt-get install libssl-dev
```

**Comment by aaronpearlman** [comment]
Results of Write, Latency, and Read tests on High Endurance NVME drives:

![image](https://user-images.githubusercontent.com/17873558/213680696-9f2fca28-41bc-43ff-8128-bb4abc5b533f.png)

**Comment by aaronpearlman** [comment]
High Endurance NVME drives mounted at the following paths with `ext4` filesystem:

`/data/chime/local/he-nvme-1`
`/data/chime/local/he-nvme-2`

![image](https://user-images.githubusercontent.com/17873558/213681028-70bdf455-9a2e-4985-ae87-73a80a94e17b.png)

**Comment by aaronpearlman** [comment]
I opened the following PR to add config updates to `kotekan`, in order to enable `outrigger-gating` as the receiver node for beam 10:

See: https://github.com/kotekan/kotekan/pull/1072

**Comment by aaronpearlman** [comment]
First light from beam 10 recording voltages on `outrigger-gating`. This completes our **initial** end-to-end test of the system.

The Crab PSR (Stokes I, detected both after folding and individual single pulses, post-coherent dedispersion):

<img width="489" alt="image" src="https://user-images.githubusercontent.com/17873558/216745802-122e077d-2499-40c6-afcd-ed689fc0b2fc.png">
<img width="278" alt="image" src="https://user-images.githubusercontent.com/17873558/216745821-fecf2a5b-0a0d-4524-a931-e488c550020a.png">
<img width="278" alt="image" src="https://user-images.githubusercontent.com/17873558/216745827-ee00bd11-9247-4fcb-a75f-f75bb84450ed.png">
<img width="277" alt="image" src="https://user-images.githubusercontent.com/17873558/216745831-d17c61bb-2555-44b5-a1c4-7191a32eb980.png">
