### ISSUE TITLE
Implement fast coherent dedispersion algorithm for baseband tracking beam

### ISSUE THREAD

**Issue by aaronpearlman** [kotekan/kotekan#1083]
Implement fast coherent dedispersion algorithm for testing the gating algorithm on baseband tracking beam data from CHIME.

- [x] Implement fast coherent DD.
- [x] Test on individual single pulses.
- [x] Test on a full PSR transit observation.

**Comment by aaronpearlman** [comment]
Results from running the new coherent DD code on a recording from the Crab PSR on 2023.05.30. Everything is working beautifully!

The new code also removes the digitization artifacts seen previously using my old code.

Folded pulse profile of the Crab after coherent and incoherent dedispersion:

![Image](https://github.com/kotekan/kotekan/assets/17873558/0450caec-b072-4163-8ef9-624f63335b1a)

Top 5 brightest giant pulses detected during the observation:

![Image](https://github.com/kotekan/kotekan/assets/17873558/e0349b88-a404-4b16-a5fd-f51f96fe7061)

![Image](https://github.com/kotekan/kotekan/assets/17873558/9328c538-b9a2-46b9-b294-a27f6840a337)

![Image](https://github.com/kotekan/kotekan/assets/17873558/282521ab-18d7-444b-9473-b16a04921cd8)

![Image](https://github.com/kotekan/kotekan/assets/17873558/77a0f17c-120d-464f-95e2-a212426885a5)

![Image](https://github.com/kotekan/kotekan/assets/17873558/3c210ff0-463b-485a-926e-1b3eda187ddb)

**Comment by aaronpearlman** [comment]
See https://github.com/kotekan/kotekan/issues/1094 for possible additional improvements.

**Comment by leungcalvin** [comment]
I will definitely have a look at you fast coherent dedispersion code for the software correlator! But just to confirm, for the tracking beam system, the correlator expects beamformed data (without any coherent desmearing) which is gated in time with a frequency-dependent time offset following the dispersive sweep. I wanted to double check that that's what you're building toward.

**Comment by aaronpearlman** [comment]
@leungcalvin Yup, that's exactly what I am building.

The reason for needing this capability as part of the development is so I can be sure that we save all of the needed information content. The only way to check this is to coherently dedisperse and fold after gating.

You will receive -- dispersed -- beamformed data, gated in time and frequency, according to the DM of the PSR calibrator.
