### ISSUE TITLE
KotekanMaster To-Do List

### ISSUE THREAD

**Issue by shinybrar** [kotekan/kotekan#69]
# July Updates 
Tracked in issue #73  
 - [x] Improve the `KotekanMaster` startup procedure by allowing problematic node connections to raise `Exception` errors.
  - [x] Propagate `startup_failures` to a restart list.
  - [x] Implement a Command Line Interface (CLI) for KotekanMaster with input from data tsars.
  - [x] Post the following endpoint updates to slack:
    - Start / Stop status.
    - Blacklisting / Whitelisting of a node.
    - Array synchronization status
    - Restart list as executed by the watchdog process.
- [x] Perform a kotekan version check at each startup.
# August Updates
- [x] Improve configuration / array synchronization logic. Possibly merge them into one state machine.
- [ ] Implement logic for sending and checking of array based parameters.
- [ ] Investigate and implement a solution for archiving / tracking the dynamic changes to the array.

# Future Updates
- [ ] Investigate using `jinja2` preprocessor for improving readability of CHIME config files.
- [ ] Testing framework for KotekanMaster wherever possible.
- [ ] Federation of eign gains over REST endpoints.

**Comment by andrerenard** [comment]
This is an old ticket that was completed (and we've since moved to `coco`)
