### ISSUE TITLE
Fixes for new github CI

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#700]
- [x] test if iwyu check still works (is activated only for master now) - @nritsche #706 
- [ ] run baseband tests on Jenkins (deactivated on github) with a single build
- [x] install redis server in docker image to activate tests that use redis
- [x] install comet
- [x] don't run the docker build step if the Dockerfile's haven't changed
- [x] black - @nritsche #707 
- [x] clang-format - @nritsche #707 
- [x] build docs - @james-s-willis #705 
- [ ] ROCm build - @andrerenard 
- [x] MacOS build ~(requires self-hosted runner)~ @nritsche #736 
  - should work on Github hosted runners.
  - can't use docker, but many of the dependencies should already be in the base Github mac env.
  - use homebrew to install the rest

**Comment by jrs65** [comment]
That was quick. I was just about to create this one!

I guess I don't understand what the point of running the baseband tests on Jenkins is?

**Comment by jrs65** [comment]
I also added a new one.

**Comment by nritsche** [comment]
> I guess I don't understand what the point of running the baseband tests on Jenkins is?

You deactivated it in the github action files, right?

**Comment by nritsche** [comment]
>  don't run the docker build step if the Dockerfile's haven't changed

I'm not sure how this would work. We can't simply check if it has changed in the last commit, because github actuions are only executed once if you push multiple commits. Is there a way to get the commit hash of the last time the action ran?

Alternatively, is there any way to compare the Dockerfile against the remote image to tell if there are changes?

**Comment by jrs65** [comment]
I'm not sure if there's a smart way to do it, but I think you could:
- Hash the dockerfile
- Pull a file with the last run hashes in from a Github Actions artifact
- If identical, don't do anything
- If changed, rebuild the docker image, push it, and update the artifact with the new hashes

A maybe cleaner thing to do might be tagging the docker image with the hash, and only build if it doesn't exist. Not sure exactly how you can check that though.

**Comment by nritsche** [comment]
> I'm not sure if there's a smart way to do it, but I think you could:
> 
>     * Hash the dockerfile
> 
>     * Pull a file with the last run hashes in from a Github Actions artifact
> 
>     * If identical, don't do anything
> 
>     * If changed, rebuild the docker image, push it, and update the artifact with the new hashes
> 

I thought about his, too. Can we do something against lots of builds if there are two parallel branches with different Dockerfile's with lots of commits?

> A maybe cleaner thing to do might be tagging the docker image with the hash, and only build if it doesn't exist. Not sure exactly how you can check that though.

This also was my other idea. I guess you could put the hash in the name/tag. But this would lead to lots of different images being pushed. How much space do we have? We would need a way to remove unused ones.
